spring:
  datasource:
#    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${MYSQL_DATABASE}
#    username: ${MYSQL_USER}
#    password: ${MYSQL_PASSWORD}
    url: jdbc:mysql://localhost:3306/fintech
    username: mustopha
    password: ayinde_99
    driver-class-name: com.mysql.cj.jdbc.Driver

    # Disable automatic table creation
    jpa:
      hibernate:
        ddl-auto: update

      # Show SQL in logs
      show-sql: true
      properties:
        hibernate:
          format_sql: false

  logging:
    level:
      org.hibernate.SQL: DEBUG
      org.hibernate.type.descriptor.sql.BasicBinder: TRACE
server:
  port: 8090
